

  const mobileNav = document.querySelector(".mobile-nav");
  const navBtn = document.querySelector("#navBtn");

  navBtn.addEventListener("click", () => {
    mobileNav.classList.toggle("active");
  });
  function toggleAccordion(index) {
    const allContents = document.querySelectorAll('[id^="content-"]');
    const allIcons = document.querySelectorAll('[id^="icon-"]');

    // SVG for Down icon
    const upSVG = `
      <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="13" cy="13" r="12.5" fill="white" stroke="#BAB5B5"/>
        <path d="M6 10L13 17L20 10" stroke="#BAB5B5" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    `;

    // SVG for Up icon
    const downSVG = `
      <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="13" cy="13" r="12.5" fill="white" stroke="#BAB5B5"/>
        <path d="M6 16L13 9L20 16" stroke="#BAB5B5" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    `;

    // Close all accordion items
    allContents.forEach((content, idx) => {
      if (idx + 1 !== index) {
        content.style.maxHeight = "0";
        allIcons[idx].innerHTML = upSVG;
      }
    });

    // Toggle the selected accordion item
    const content = document.getElementById(`content-${index}`);
    const icon = document.getElementById(`icon-${index}`);

    if (content.style.maxHeight && content.style.maxHeight !== "0px") {
      content.style.maxHeight = "0";
      icon.innerHTML = upSVG;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
      icon.innerHTML = downSVG;
    }
  }
    const faqs = [
      {
        question: "What is Teal Climate?",
        answer:
          "Teal Climate is a SaaS platform helping businesses and institutions measure, manage, and reduce their carbon emissions.",
      },
      {
        question: "Who can use Teal Climate?",
        answer:
          "Our platform is designed for organizations of all sizes, including those in finance, real estate, service, and manufacturing sectors.",
      },
      {
        question: "Is the platform compliant with the GHG Protocol?",
        answer:
          "Yes, our methodologies align with the Greenhouse Gas Protocol and other global standards.",
      },
      {
        question: "How can I get started?",
        answer:
          "Simply sign up for a plan that fits your needs and begin your carbon accounting journey today.",
      },
      {
        question: "Is customer support available?",
        answer:
          "Yes, our dedicated support team is available via email and we can schedule calls to further assist you in your decarbonization journey.",
      },
      {
        question: "Does Teal Climate provide API access?",
        answer:
          "Yes, we offer robust API access for Enterprise customers, enabling seamless integration with ERP systems, CRM tools, and other third-party platforms.",
      },
      {
        question: "How secure is my data on Teal Climate?",
        answer:
          "We prioritize data security and comply with global standards such as GDPR. All data is encrypted both in transit and at rest, and we conduct regular security audits to safeguard your information.",
      },
      {
        question: "Can I customize reports generated by Teal Climate?",
        answer:
          "Yes, our platform allows extensive customization of reports, including selecting specific metrics, time frames, and visualization formats. Professional and Enterprise plans include additional advanced reporting features.",
      },
      {
        question:
          "What data formats does Teal Climate support for data upload?",
        answer:
          "Teal Climate supports multiple formats, including CSV, Excel, and JSON. We also offer custom data-mapping tools to ensure seamless integration with your existing data.",
      },
      {
        question: "What is the uptime guarantee for the Teal Climate platform?",
        answer:
          "We ensure 99.9% uptime, backed by our high-availability infrastructure and proactive monitoring systems.",
      },
      {
        question: "Can I integrate Teal Climate with my existing systems?",
        answer:
          "Absolutely! Our API and integration support make the process seamless.",
      },
      {
        question: "Can I export my data from Teal Climate?",
        answer:
          "Yes, all data and reports can be exported in various formats, including CSV, PDF, and Excel, making it easy to share insights with stakeholders.",
      },
  ];
  
function renderFAQs(containerId, limit = null) {
  const faqSection = document.getElementById(containerId);

  if (!faqSection) {
    return;
  }

  const toRender = limit ? faqs.slice(0, limit) : faqs;

  faqSection.innerHTML = "";
  toRender.forEach((faq, index) => {
    faqSection.innerHTML += `
      <div class="faq-item">
        <button
          onclick="toggleAccordion(${index + 1})"
          class="faq-button"
        >
          <span class="faq-question">${faq.question}</span>
          <span
            id="icon-${index + 1}"
            class="faq-icon"
          >
          <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="13" cy="13" r="12.5" fill="white" stroke="#BAB5B5"/>
        <path d="M6 10L13 17L20 10" stroke="#BAB5B5" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
          </span>
        </button>
        <div
          id="content-${index + 1}"
          class="faq-content"
        >
          <div class="faq-answer">
            ${faq.answer}
          </div>
        </div>
      </div>
    `;
  });
}

  renderFAQs("faq-section1",6);
  renderFAQs("faq-section2");

  // Make the function globally accessible
  window.toggleAccordion = toggleAccordion;
